default_language_version:
    python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
        description: This hook checks json files for parseable syntax.
      - id: check-yaml
        description: This hook checks yaml files for parseable syntax.
      - id: check-toml
        description: This hook checks toml files for parseable syntax.
      - id: check-ast
        description: Simply check whether files parse as valid python.
      - id: check-merge-conflict
        description: Check for files that contain merge conflict strings.
      - id: debug-statements
        description: Check for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: end-of-file-fixer
        description: Ensures that a file is either empty, or ends with one newline.
      - id: name-tests-test
        description: This verifies that test files are named correctly - test* format (prefix and not suffix)
        args: ["--django"]
      - id: no-commit-to-branch
        args: [-b, develop, -b, master, -b, main]
        description: Don't commit to branch develop/master
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,markdown"]
        description: This hook trims trailing whitespace.
      - id: jinjalint
        description: This hook checks html files for parseable syntax.
      - id: csslint
        description: This hook checks css files for parseable syntax.
  # Make sure we use an up-to-date python syntax
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
  # Hooks to run locally
  # Pre-commit is installed by poetry alongside black, isort, flake8
  # to make sure we don't track version of black/isort/flake8 in 2 seperate configs
  # we set pre-commit to use black/isort/flake8 installed by poetry
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        language: system
        require_serial: true
        types: [python]
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8 --config .flake8
        language: system
        types: [python]